### ISSUE TITLE
Empty index query: Improve error explanation?

### ISSUE THREAD

**Issue by traud** [Debian/dcs#110]
My Regular Expression (RegEx), [explained on debian-devel](https://lists.debian.org/debian-devel/2021/11/msg00135.html), returns:
```
Error: Loading search result package list failed:
This query was refused by the server: Empty index query
```
works: `\x2f\x2a\x40\x7d` avoids escaping errors (HTML, RegEx engine, you never know)
works: `/\*@}` escape for the star required
works: `/\*\s+@}` at least one whitespace character between `/*` and `@}`
not: `/\*\s*@}` whitespace optional
not: `[^/]//\s*@}` same issue but C++ style comment pattern, like `//@}`

Going through the underlying Bachelor thesis, the search tree has problems with optional whitespace, I guess. In my case, I worked around it by searching without whitespace and again with at least one whitespace. Anyway, is it possible to improve the error massage, for example by linking to the Bachelor thesis (or by explaining the search tree stuff in short form), when RegEx was selected?

**Comment by stapelberg** [comment]
> Going through the underlying Bachelor thesis, the search tree has problems with optional whitespace, I guess.

I don’t think the problem is specific to whitespace. I can reproduce it also with `/\*a*@}`.

I think the problem is related to the code not finding enough consecutive non-optional characters to construct any trigrams to query the index with. In other words: your regexp has a too short start, and a too short end, with too much optionality in the middle :)

I can add an entry to the faq and link to it from the error message.

**Comment by traud** [comment]
Ahh. Then the error is about having too much ‘optionality’ and my approach splitting it into two distinct, more specific queries (one with at least one space, and one with no space at all) was the way to go. Thanks for clarifying!
